name: "Sync Subnet EVM Branch" 
on:
  workflow_dispatch:
      inputs:
        remoteBranch:
            description: "Subnet EVM Branch"
            required: true
            default: "coreth-test-0"

jobs:
    sync_branch:
        name: Sync Subnet EVM Branch
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-go@v5
            with:
              go-version: "~1.21.12"
              check-latest: true

          - name: Add Remote
            run: |
              git remote add subnet-evm https://github.com/ava-labs/subnet-evm
        
          # TODO: Can use default when we remove the push trigger hack
          # TODO: Replace test branch with actual (eg, coreth)
          - name: Fetch Remote Branch (${{ github.event.inputs.remoteBranch }})
            run: |
              git fetch subnet-evm ${{ github.event.inputs.remoteBranch }}
              git fetch subnet-evm coreth-diff-script
              git branch -a # Verify the new branch was fetched

          # TODO: Remove this step when the script is checked in
          - name: Checkout script
            run: |
              git checkout subnet-evm/coreth-diff-script -- ./scripts/apply_diff_and_rename.sh

          - name: Apply diff
            run: |
              ./scripts/apply_diff_and_rename.sh subnet-evm/${{ github.event.inputs.remoteBranch }}

          # TODO: Should this step be removed?
          - name: Restore .github/workflows
            run: |
              git checkout -- .github/workflows

          # TODO: Add subnet-evm commit hash
          - name: Create Pull Request
            uses: peter-evans/create-pull-request@v6
            with:
              commit-message: "Automated commit message"
              branch: auto-sync-subnet-evm
              title: "Sync Subnet EVM"
              body: |
                This PR was created automatically by a GitHub Action.
              draft: true
