name: "Sync Subnet EVM Branch" 
on:
  push:
    branches:
      - sync-subnet-evm-branch # Hack to trigger workflow
  workflow_dispatch:
      inputs:
        remoteBranch:
            description: "Subnet EVM Branch"
            required: true
            default: "coreth-test-0"

jobs:
    sync_branch:
        name: Sync Subnet EVM Branch
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v4

          - uses: actions/setup-go@v5
            with:
              go-version: "~1.21.12"
              check-latest: true

          - name: Add Remote
            run: |
              git remote add -f subnet-evm ava-labs/subnet-evm
              git remote -v # Verify the new remote was added
        
          - name: Fetch Remote Branch (${{ github.events.inputs.remoteBranch }})
            run: |
              git fetch ${{ github.events.inputs.remoteBranch }}
              git branch -a # Verify the new branch was fetched