name: "Sync Subnet EVM Branch" 
on:
  workflow_dispatch:
      inputs:
        remoteBranch:
            description: "Subnet EVM Branch"
            required: true
            default: "coreth-test-0"

jobs:
    sync_branch:
        name: Sync Subnet EVM Branch
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/setup-go@v5
            with:
              go-version: "~1.21.12"
              check-latest: true

          - name: Add Remote
            run: |
              git remote add -f subnet-evm git@github.com:ava-labs/subnet-evm.git
              git remote -v # Verify the new remote was added
        